project setup and example scenario
LiveIntent/castle pull request #11
Opened 2020-11-17 13:10 UTC by atalive

2020-11-17 15:36 UTC, gipeshka commented on fixures/http/live-pixel/response/1.js
> +module.exports = {
I suppose `1.js` isn't a good name for a response-fixture file

2020-11-17 16:58 UTC, jankoulaga requested changes

2020-11-17 16:58 UTC, jankoulaga commented on app/converter-streaming/data-builder.js
> +const midasKeys = require('../../constants/midas-keys')
We don't need this file at all any more.

2020-11-17 16:58 UTC, jankoulaga commented on app/converter-streaming/data-producer.js
> +const stageNames = require('../../constants/stages')
No more data-producers.

2020-11-17 16:58 UTC, jankoulaga commented on domain/command.js
> +class Command {
A command will be either a http call, or kinesis, or something. This code doesn't really do much.

2020-11-17 16:58 UTC, jankoulaga commented on fixures/http/live-pixel/request/request-builder.js
> +const queryString = require('query-string')
You don't need the request builder. You should compose the request to fit the library you're using, so we don't need extra code to manipulate thing unnecessarily.

2020-11-17 16:58 UTC, jankoulaga commented on scopes/live-pixel/1.js
> +async function makeLivePixelHttpRequest(id, description, scope) {
We don't want to create scopes for each test manually. The scope should be created from a scenario definition and tbh, i think you're digressing from the scope of the ticket.

2020-11-17 16:58 UTC, jankoulaga commented on clients/http/live-pixel.js
> +const https = require('https')
We don't want a live-pixel client. we want an http client that can do any kind of request, get,post, head, whatever.

2020-11-17 16:58 UTC, jankoulaga commented on app/live-pixel/live-pixel-client.js
> +            console.log('response . . . . ', response.statusCode, response.headers)
Let's start logging things correctly already. Let's add meaningful log lines, use different log levels that we might want to see depending on how we run the project.

2020-11-18 16:07 UTC, atalive commented on fixures/http/live-pixel/response/1.js
> +module.exports = {
I changed now. but we will decide after

2020-11-18 16:08 UTC, atalive commented on domain/command.js
> +class Command {
refactored to ne http command

2020-11-18 19:24 UTC, jankoulaga commented on clients/http.js
> +async function get(serviceName, options) {
But why? You don't need this at all. All this can be in the HttpCommand, and the service name is completely irrelevant. The request will go out to anything that's set as the uri in the options.

2020-11-18 19:28 UTC, jankoulaga commented on domain/httpCommand.js
> +class httpCommand {
Classes should be uppercased. Also, you'd breaking our naming convention in the file name. We agreed on kebab case

2020-11-18 19:32 UTC, jankoulaga commented on fixures/http/live-pixel/response/lp1.js
> +function nonEmpty(value) {
This has to live somewhere else, not in each fixture.

2020-11-19 10:51 UTC, atalive commented on fixures/http/live-pixel/response/lp1.js
> +function nonEmpty(value) {
moved it to another file.

2020-11-19 10:51 UTC, atalive commented on domain/httpCommand.js
> +class httpCommand {
refactored

2020-11-19 10:52 UTC, atalive commented on clients/http.js
> +async function get(serviceName, options) {
moved the http call to be in the command.

2020-11-19 10:52 UTC, atalive commented on fixures/http/live-pixel/request/request-builder.js
> +const queryString = require('query-string')
removed

2020-11-19 11:22 UTC, jankoulaga commented on domain/http-command.js
> +    trimObjectPropertiesToMatchExpected(object, expected) {
Keep in mind that we'll need to extract this into a different object later on... 

Even better, if we create a Command class as an interface which contains this and the difference functions, then each Command subtype will inherit those...

Something like:

```
class Command {
   trimObjectPropertiesblabla(...)  { ... }
}

class HttpCommand extends Command {
.....
}
```

2020-11-19 11:27 UTC, jankoulaga commented on domain/http-command.js
> +            let formattedResponse = this.trimObjectPropertiesToMatchExpected(response, responseFixture)
Here you're expecting a single response, but there might be redirects, so i think you should capture `response.redirects`. In case of a simple 200 it should return a single response array, in case of multiple redirects(which we'll need to test with ipv6 and cookie bounce) we'll have to specify an array in the expectation. 

That's also why your difference function needs to be smarter to also check for arrays.

2020-11-19 11:28 UTC, jankoulaga commented on package.json
> +    "immutable": "^4.0.0-rc.12",
Where are you using this?

2020-11-19 11:29 UTC, jankoulaga commented on fixures/macros.js
> +    return (typeof value !== 'undefined')
This is not really true, as an empty string will return true, yet we expect it to be non empty

2020-11-19 11:34 UTC, jankoulaga commented on domain/http-command.js
> +            this.scenario.state = comparisonResult ? status.failed : this.response
state should not be set like this. The state itself has to be something like what we do in LiveConnect where we append the incoming data with what's already there. And you don't need the execution queue.

2020-11-19 11:36 UTC, jankoulaga commented
@atalive you need to revert back the circleci config and actually use it. Otherwise we have no idea what's going on in this project.

2020-11-19 16:33 UTC, atalive commented on domain/http-command.js
> +    trimObjectPropertiesToMatchExpected(object, expected) {
moved the common functions to Command class to extend from

2020-11-19 16:34 UTC, atalive commented on domain/http-command.js
> +            let formattedResponse = this.trimObjectPropertiesToMatchExpected(response, responseFixture)
Added a check for redirects to compare the redirect response instead of the final one

2020-11-19 16:36 UTC, atalive commented on domain/http-command.js
> +            let formattedResponse = this.trimObjectPropertiesToMatchExpected(response, responseFixture)
But need to test this and figure out what to store in the state in this case. Is now the whole response.

2020-11-19 16:36 UTC, atalive commented on package.json
> +    "immutable": "^4.0.0-rc.12",
not using. was a part of my experiment with macros

2020-11-19 16:37 UTC, atalive commented on fixures/macros.js
> +    return (typeof value !== 'undefined')
don't know if it is right but returning the value now that is after checked like `if(value)` which covers all the cases.

2020-11-19 16:38 UTC, atalive commented on domain/http-command.js
> +            this.scenario.state = comparisonResult ? status.failed : this.response
refactored to keep the execution results in the state. My approach was to keep only the last result in the state.

2020-11-19 17:10 UTC, jankoulaga commented on commands/http-command.js
> +            }
Why? We want the whole response in a form of an array.

2020-11-19 17:14 UTC, jankoulaga commented on commands/http-command.js
> +            this.scenario.state[this.description] = comparisonResult ? comparisonResult : status.passed
This  is not want we want to store there. First of all, we never said we should solve this problem right now, and since it's creating a ton of confusion, just remove it for now.

2020-11-19 17:14 UTC, jankoulaga commented on fixures/http/live-pixel/response/lp1.js
> +module.exports = {
still not an array... I think i've commented on the same thing 3x.

2020-11-19 17:16 UTC, jankoulaga commented on macros.js
> +exports.nonEmpty = value => {
this should return a boolean. so i guess !!value

2020-11-19 17:32 UTC, jankoulaga commented on macros.js
> +exports.nonEmpty = value => {
And i think we agreed that these are not really macros.

2020-11-20 10:46 UTC, atalive commented on commands/http-command.js
> +            }
returning the whole request now and checking in fixtures

2020-11-20 10:46 UTC, atalive commented on commands/http-command.js
> +            this.scenario.state[this.description] = comparisonResult ? comparisonResult : status.passed
removed

2020-11-20 10:47 UTC, atalive commented on fixures/http/live-pixel/response/lp1.js
> +module.exports = {
verifying in the fixture for a redirect case for an array

2020-11-20 10:47 UTC, atalive commented on macros.js
> +exports.nonEmpty = value => {
renamed. But working on replacing this with macros. I think I have the solution now.

2020-11-20 10:48 UTC, atalive commented on macros.js
> +exports.nonEmpty = value => {
refactored

2020-11-20 16:29 UTC, jankoulaga commented on domain/command.js
> +module.exports = Command
```suggestion
module.exports = Command

```

2020-11-20 16:30 UTC, jankoulaga commented on helpers.js
> +exports.nonEmpty = value => {
This is not used.

2020-11-20 16:31 UTC, jankoulaga commented on scenarios/llive-pixel/lp1.js
> +const httpCommand = require('../../commands/http-command')
```suggestion
const HttpCommand = require('../../commands/http-command')
```

2020-11-22 19:52 UTC, atalive commented on helpers.js
> +exports.nonEmpty = value => {
removed

2020-11-22 19:53 UTC, jankoulaga approved these changes

2020-11-23 13:21 UTC, merged